sudo: false
language: node_js

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache

matrix:
  include:
    - os: linux
      node_js: "7"
      env: JOB_NAME=test
    - os: linux
      node_js: "6"
      env: JOB_NAME=test
    - os: linux
      node_js: "4.3"
      env: JOB_NAME=test
  allow_failures:
    - os: osx
  fast_finish: true

script: npm run travis:$JOB_NAME
